In [3]:
import pyDOE2

# FIB-driven Gallium implantation

<img src="data/IMG_2470.JPG" width="900px">

* Dose: 1-40 fC/&mu;m<sup>2</sup> (20 fC/&mu;m<sup>2</sup> &plusmn; 10)
* Acceleration voltage: 12-20 kV
* -1500% overlap (can go down to -3000%


Fix chip with carbon tape
Cleaning with chloroform + annealing 

1. Define a rectangle of 2 by 2 &mu;m
2. Set the parameters specified in the table below

Determine the dwell time range so the dwell time ranges from 1 to 40 fC/&mu;m<sup>2</sup>
What is the beam current? 

| BEAM CURRENT | ACCELERATION VOLTAGE | OVERLAP | DWELL TIME | DOSE | FOCUS | COMMENT | 
|--:|--:|--:|--:|--:|--:|--:|
| 1pA   | 5 kV  | -1500 ||| YES || 
| 1pA   | 10 kV | -1500 ||| YES || 
| 1pA   | 15 kV | -1500 ||| YES || 
| 10pA  | 5 kV  | -1500 ||| YES || 
| 10pA  | 10 kV | -1500 ||| YES || 
| 10pA  | 15 kV | -1500 ||| YES ||
| 100pA | 5 kV  | -1500 ||| YES || 
| 100pA | 10 kV | -1500 ||| YES || 
| 100pA | 15 kV | -1500 ||| YES ||

The factors in the experiment are:
1. Acceleration voltage: 1 kV - 30 kV
2. Beam current: 1 pA - 1000 pA
3. Dose (z-size): 1 fC/&mu;m<sup>2</sup> - 40 fC/&mu;m<sup>2</sup>
4. Dwell time: 100 ns - 1000 ns
5. Overlap percentage: 0 to -1500%

The z-size is automatically determined as the desired dose is given.

For the first experiment, we fix the dwell time and the overlap percentage. Dwell time is fixed at 100 ns, and overlap percentage is set to -1500% (as suggested by Jeppe). 

1. Acceleration voltage [V]: 1 kV - 30 kV
2. Beam current [I]: 1 pA - 1000 pA
3. Dose (z-size) [D]: 1 fC/&mu;m<sup>2</sup> - 40 fC/&mu;m<sup>2</sup>


In [7]:
factors = 3
design = pyDOE2.fullfact([2]*factors)
print("Full Factorial Design (coded as -1 for low level and +1 for high level):")
print(design*2-1)  # Convert 0 to -1 and 1 to +1 for the traditional coding of full factorial designs

Full Factorial Design (coded as -1 for low level and +1 for high level):
[[-1. -1. -1.]
 [ 1. -1. -1.]
 [-1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [ 1.  1.  1.]]


In [8]:
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.formula.api import ols

# Let's assume we have some response data from our experiment.
# Replace these values with your actual experimental results.
responses = [20, 30, 25, 45]  # Hypothetical response data for the 4 runs

# Factorial design from the previous example
design = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])

# We need to add a constant term to include the intercept in our model
X = sm.add_constant(design)

# Fit the ANOVA model
model = ols('data ~ C(factor1) + C(factor2) + C(factor1):C(factor2)', data={'data': responses, 'factor1': X[:,1], 'factor2': X[:,2]}).fit()

# Print the ANOVA table
anova_results = sm.stats.anova_lm(model, typ=2)
print(anova_results)

# Create main effects plot
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.title('Main Effects Plot')
plt.plot([-1, 1], [np.mean(responses[:2]), np.mean(responses[2:])], label='Factor 1')
plt.plot([-1, 1], [np.mean(responses[::2]), np.mean(responses[1::2])], label='Factor 2')
plt.xlabel('Level')
plt.ylabel('Mean Response')
plt.xticks([-1, 1], ['Low', 'High'])
plt.legend()

# Create interaction plot
plt.subplot(1, 2, 2)
plt.title('Interaction Plot')
plt.plot([-1, 1], [responses[0], responses[1]], label='Factor 1 at Low')
plt.plot([-1, 1], [responses[2], responses[3]], label='Factor 1 at High')
plt.xlabel('Factor 2 Level')
plt.ylabel('Response')
plt.xticks([-1, 1], ['Low', 'High'])
plt.legend()

plt.tight_layout()
plt.show()


C:\Users\vazqu\anaconda3\Lib\site-packages\statsmodels\regression\linear_model.py:1716: RuntimeWarning: divide by zero encountered in scalar divide
  return np.dot(wresid, wresid) / self.df_resid


ValueError: array must not contain infs or NaNs